kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: makoto126/xfsquota
    dockerfile: xfsquota/Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    
